default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: shopify_dev

test:
  <<: *default
  database: shopify_test

production:
  <<: *default
  database: shopify_prod
